name: Azure Node.js Express.js Deploy

on:
  push:
    branches:
      - main  # Cambia a 'master' si tu rama principal es master.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Cambia a la versión que estés usando

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: |
        npm run build  # Si tienes un script de build en tu package.json
        # Si no tienes un script de build, puedes eliminar esta línea

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .


 
